# Generated by Django 5.1.7 on 2025-03-13 15:33

import apps.core.models.data_file
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('published', 'Published')], default='pending', max_length=20)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.core.models.data_file.file_upload_path)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('pdf', 'PDF'), ('parquet', 'Parquet'), ('json', 'JSON'), ('xml', 'XML'), ('other', 'Other')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('validated', 'Validated'), ('error', 'Error'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('md5_hash', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.dataset')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='core.institution'),
        ),
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='processed/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(default=0.0)),
                ('processing_metadata', models.JSONField(blank=True, default=dict)),
                ('quality_score', models.FloatField(default=0.0)),
                ('row_count', models.IntegerField(default=0)),
                ('validation_results', models.JSONField(blank=True, default=dict)),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_data', to='core.datafile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together={('institution', 'name', 'version')},
        ),
    ]
